import { ETrangThaiNguyenLieu, INguyenLieu, IStatKho } from './typing';

export const DANH_SACH_NGUYEN_LIEU: INguyenLieu[] = [
  {
    id: 'nl1',
    ten: 'Gạo Bắc Hương',
    donVi: 'kg',
    nhaCungCap: 'Vinaseed',
    tonKho: 48,
    mucToiThieu: 20,
    giaNhap: 22000,
    trangThai: ETrangThaiNguyenLieu.DU_HANG,
  },
  {
    id: 'nl2',
    ten: 'Thịt bò thăn',
    donVi: 'kg',
    nhaCungCap: 'Vissan',
    tonKho: 8,
    mucToiThieu: 10,
    giaNhap: 320000,
    trangThai: ETrangThaiNguyenLieu.SAP_HET,
  },
  {
    id: 'nl3',
    ten: 'Cà phê hạt',
    donVi: 'kg',
    nhaCungCap: 'Highlands',
    tonKho: 14,
    mucToiThieu: 5,
    giaNhap: 280000,
    trangThai: ETrangThaiNguyenLieu.DU_HANG,
  },
  {
    id: 'nl4',
    ten: 'Trà đào syrup',
    donVi: 'L',
    nhaCungCap: 'Monin',
    tonKho: 2,
    mucToiThieu: 5,
    giaNhap: 180000,
    trangThai: ETrangThaiNguyenLieu.SAP_HET,
  },
  {
    id: 'nl5',
    ten: 'Rau muống',
    donVi: 'kg',
    nhaCungCap: 'Vườn Xanh',
    tonKho: 3,
    mucToiThieu: 10,
    giaNhap: 15000,
    trangThai: ETrangThaiNguyenLieu.SAP_HET,
  },
  {
    id: 'nl6',
    ten: 'Đường cát',
    donVi: 'kg',
    nhaCungCap: 'Biên Hòa',
    tonKho: 0,
    mucToiThieu: 15,
    giaNhap: 24000,
    trangThai: ETrangThaiNguyenLieu.HET_HANG,
  },
  {
    id: 'nl7',
    ten: 'Dầu ăn',
    donVi: 'L',
    nhaCungCap: 'Vinaseed',
    tonKho: 12,
    mucToiThieu: 5,
    giaNhap: 55000,
    trangThai: ETrangThaiNguyenLieu.DU_HANG,
  },
  {
    id: 'nl8',
    ten: 'Nước mắm',
    donVi: 'L',
    nhaCungCap: 'Monin',
    tonKho: 8,
    mucToiThieu: 3,
    giaNhap: 70000,
    trangThai: ETrangThaiNguyenLieu.DU_HANG,
  },
  {
    id: 'nl9',
    ten: 'Bún tươi',
    donVi: 'kg',
    nhaCungCap: 'Highlands',
    tonKho: 20,
    mucToiThieu: 8,
    giaNhap: 28000,
    trangThai: ETrangThaiNguyenLieu.DU_HANG,
  },
  {
    id: 'nl10',
    ten: 'Trân châu',
    donVi: 'kg',
    nhaCungCap: 'Biên Hòa',
    tonKho: 15,
    mucToiThieu: 8,
    giaNhap: 120000,
    trangThai: ETrangThaiNguyenLieu.DU_HANG,
  },
];

export const STAT_KHO: IStatKho = {
  tongNguyenLieu: 10,
  sapHetHet: 4,
  giaTri: '10tr',
  nhaCungCap: 6,
};

export const CAN_NHAP_THEM: string[] = [
  'Thịt bò thăn',
  'Trà đào syrup',
  'Rau muống',
  'Đường cát',
];

export const TRANG_THAI_CONFIG: Record<ETrangThaiNguyenLieu, { label: string; color: string; bg: string; barColor: string }> = {
  [ETrangThaiNguyenLieu.DU_HANG]:  { label: 'Đủ hàng',  color: '#16a34a', bg: '#f0fdf4', barColor: '#22c55e' },
  [ETrangThaiNguyenLieu.SAP_HET]:  { label: 'Sắp hết',  color: '#d97706', bg: '#fffbeb', barColor: '#f59e0b' },
  [ETrangThaiNguyenLieu.HET_HANG]: { label: 'Hết hàng', color: '#dc2626', bg: '#fef2f2', barColor: '#ef4444' },
};
