import { EDanhMuc, IMonAn } from './typing';

export const DANH_SACH_MON: IMonAn[] = [
  {
    id: 'm1',
    ten: 'Cơm chiên Dương Châu',
    moTa: 'Cơm chiên thơm ngon với trứng, tôm, xúc xích',
    danhMuc: EDanhMuc.MON_CHINH,
    giaBan: 40000,
    thoiGian: 15,
    calo: 520,
    danhGia: 4.5,
    isHot: false,
    mauNen: 'linear-gradient(135deg, #f59e0b 0%, #ef4444 100%)',
    coSan: true,
  },
  {
    id: 'm2',
    ten: 'Bún đậu mắm tôm',
    moTa: 'Bún đậu tươi kèm mắm tôm đặc trưng',
    danhMuc: EDanhMuc.MON_CHINH,
    giaBan: 55000,
    thoiGian: 10,
    calo: 480,
    danhGia: 4.8,
    isHot: true,
    mauNen: 'linear-gradient(135deg, #f97316 0%, #dc2626 100%)',
    coSan: true,
  },
  {
    id: 'm3',
    ten: 'Phở bò tái',
    moTa: 'Phở bò truyền thống với nước dùng trong vắt',
    danhMuc: EDanhMuc.MON_CHINH,
    giaBan: 45000,
    thoiGian: 20,
    calo: 560,
    danhGia: 4.7,
    isHot: true,
    mauNen: 'linear-gradient(135deg, #8b5cf6 0%, #ec4899 100%)',
    coSan: true,
  },
  {
    id: 'm4',
    ten: 'Canh chua cá lóc',
    moTa: 'Canh chua đậm đà vị miền Nam truyền thống',
    danhMuc: EDanhMuc.MON_CHINH,
    giaBan: 40000,
    thoiGian: 25,
    calo: 310,
    danhGia: 4.4,
    isHot: false,
    mauNen: 'linear-gradient(135deg, #06b6d4 0%, #3b82f6 100%)',
    coSan: true,
  },
  {
    id: 'm5',
    ten: 'Trà đào cam sả',
    moTa: 'Trà đào thơm mát kết hợp cam sả tươi',
    danhMuc: EDanhMuc.DO_UONG,
    giaBan: 22000,
    thoiGian: 5,
    calo: 120,
    danhGia: 4.6,
    isHot: false,
    mauNen: 'linear-gradient(135deg, #f59e0b 0%, #f97316 100%)',
    coSan: true,
  },
  {
    id: 'm6',
    ten: 'Cà phê sữa đá',
    moTa: 'Cà phê đậm đặc, sữa béo ngậy, đá mát lạnh',
    danhMuc: EDanhMuc.DO_UONG,
    giaBan: 25000,
    thoiGian: 5,
    calo: 180,
    danhGia: 4.9,
    isHot: false,
    mauNen: 'linear-gradient(135deg, #78350f 0%, #92400e 100%)',
    coSan: true,
  },
  {
    id: 'm7',
    ten: 'Trà sữa trân châu',
    moTa: 'Trà sữa thơm ngon với trân châu dẻo mềm',
    danhMuc: EDanhMuc.DO_UONG,
    giaBan: 30000,
    thoiGian: 7,
    calo: 250,
    danhGia: 4.8,
    isHot: true,
    mauNen: 'linear-gradient(135deg, #7c3aed 0%, #db2777 100%)',
    coSan: true,
  },
  {
    id: 'm8',
    ten: 'Chả giò rế',
    moTa: 'Chả giò giòn rụm, nhân thịt heo và rau củ',
    danhMuc: EDanhMuc.AN_VAT,
    giaBan: 25000,
    thoiGian: 12,
    calo: 340,
    danhGia: 4.5,
    isHot: false,
    mauNen: 'linear-gradient(135deg, #d97706 0%, #b45309 100%)',
    coSan: true,
  },
  {
    id: 'm9',
    ten: 'Salad ức gà',
    moTa: 'Salad tươi mát với ức gà áp chảo và rau sốt chanh leo',
    danhMuc: EDanhMuc.AN_VAT,
    giaBan: 38000,
    thoiGian: 10,
    calo: 280,
    danhGia: 4.6,
    isHot: false,
    mauNen: 'linear-gradient(135deg, #16a34a 0%, #059669 100%)',
    coSan: true,
  },
  {
    id: 'm10',
    ten: 'Bánh mì thịt nướng',
    moTa: 'Bánh mì giòn với thịt nướng thơm lừng',
    danhMuc: EDanhMuc.AN_VAT,
    giaBan: 28000,
    thoiGian: 8,
    calo: 420,
    danhGia: 4.7,
    isHot: true,
    mauNen: 'linear-gradient(135deg, #ea580c 0%, #dc2626 100%)',
    coSan: true,
  },
  {
    id: 'm11',
    ten: 'Đậu hũ sốt cà chua',
    moTa: 'Đậu hũ mềm mịn, sốt cà chua đậm đà',
    danhMuc: EDanhMuc.MON_CHAY,
    giaBan: 35000,
    thoiGian: 18,
    calo: 260,
    danhGia: 4.3,
    isHot: false,
    mauNen: 'linear-gradient(135deg, #dc2626 0%, #b91c1c 100%)',
    coSan: true,
  },
  {
    id: 'm12',
    ten: 'Đậu hũ chiên xả ớt',
    moTa: 'Đậu hũ chiên vàng, xào xả ớt thơm cay',
    danhMuc: EDanhMuc.MON_CHAY,
    giaBan: 30000,
    thoiGian: 15,
    calo: 300,
    danhGia: 4.5,
    isHot: true,
    mauNen: 'linear-gradient(135deg, #16a34a 0%, #15803d 100%)',
    coSan: true,
  },
];

export const SO_LUONG_THEO_DANH_MUC: Record<string, number> = {
  tat_ca: 12,
  mon_chinh: 4,
  do_uong: 3,
  an_vat: 3,
  mon_chay: 2,
};
