import { ELoaiGiamGia, ELoaiGiaCombo, ETrangThaiKhuyenMai, ICombo, IKhuyenMai, IStatKhuyenMai } from './typing';

export const DANH_SACH_KHUYEN_MAI: IKhuyenMai[] = [
  {
    id: 'km1',
    ma: 'LUNCH20',
    ten: 'Giảm 20% combo trưa',
    moTa: 'Giảm 20% · Đơn từ 50.000đ',
    loai: ELoaiGiamGia.PHAN_TRAM,
    giaTriGiam: 20,
    donToiThieu: 50000,
    daDung: 142,
    gioiHan: 500,
    hetHan: '30/6/2026',
    trangThai: ETrangThaiKhuyenMai.DANG_CHAY,
    hoatDong: true,
  },
  {
    id: 'km2',
    ma: 'NEWBIE',
    ten: 'Đơn đầu tiên giảm 15k',
    moTa: 'Giảm 15.000đ · Đơn từ 30.000đ',
    loai: ELoaiGiamGia.SO_TIEN,
    giaTriGiam: 15000,
    donToiThieu: 30000,
    daDung: 28,
    gioiHan: 100,
    hetHan: '31/12/2026',
    trangThai: ETrangThaiKhuyenMai.DANG_CHAY,
    hoatDong: true,
  },
  {
    id: 'km3',
    ma: 'SUMMER30',
    ten: 'Combo mùa hè giảm 30%',
    moTa: 'Giảm 30% · Đơn từ 80.000đ',
    loai: ELoaiGiamGia.PHAN_TRAM,
    giaTriGiam: 30,
    donToiThieu: 80000,
    daDung: 94,
    gioiHan: 100,
    hetHan: '15/7/2026',
    trangThai: ETrangThaiKhuyenMai.SAP_HET,
    hoatDong: true,
  },
  {
    id: 'km4',
    ma: 'FREESHIP',
    ten: 'Miễn phí giao hàng',
    moTa: 'Miễn ship · Đơn từ 60.000đ',
    loai: ELoaiGiamGia.MIEN_SHIP,
    giaTriGiam: 0,
    donToiThieu: 60000,
    daDung: 213,
    gioiHan: 500,
    hetHan: '30/9/2026',
    trangThai: ETrangThaiKhuyenMai.DANG_CHAY,
    hoatDong: true,
  },
  {
    id: 'km5',
    ma: 'WEEKEND',
    ten: 'Giảm 10% cuối tuần',
    moTa: 'Giảm 10% · Đơn từ 40.000đ',
    loai: ELoaiGiamGia.PHAN_TRAM,
    giaTriGiam: 10,
    donToiThieu: 40000,
    daDung: 45,
    gioiHan: 200,
    hetHan: '31/8/2026',
    trangThai: ETrangThaiKhuyenMai.TAM_DUNG,
    hoatDong: false,
  },
  {
    id: 'km6',
    ma: 'MAY2025',
    ten: 'Sinh nhật 5 năm giảm 25%',
    moTa: 'Giảm 25% · Đơn từ 50.000đ',
    loai: ELoaiGiamGia.PHAN_TRAM,
    giaTriGiam: 25,
    donToiThieu: 50000,
    daDung: 107,
    gioiHan: 200,
    hetHan: '1/5/2026',
    trangThai: ETrangThaiKhuyenMai.HET_HAN,
    hoatDong: false,
  },
];

export const STAT_KHUYEN_MAI: IStatKhuyenMai = {
  dangHoatDong: 3,
  luotSuDung: 629,
  doanhThuTao: '12.4tr',
  tyLeChuyenDoi: 62,
};

export const DANH_SACH_COMBO: ICombo[] = [
  {
    id: 'cb1',
    ten: 'Combo cơm trưa',
    moTa: 'Cơm chiên kết hợp trà đào mát lạnh',
    monAnIds: ['m1', 'm5'],
    loaiGia: ELoaiGiaCombo.PHAN_TRAM,
    giaTriGiam: 10,
    hetHan: '30/6/2026',
    trangThai: ETrangThaiKhuyenMai.DANG_CHAY,
    hoatDong: true,
  },
  {
    id: 'cb2',
    ten: 'Combo bánh mì & trà sữa',
    moTa: 'Bữa xế chiều hoàn hảo',
    monAnIds: ['m10', 'm7'],
    loaiGia: ELoaiGiaCombo.GIA_CO_DINH,
    giaTriGiam: 50000,
    hetHan: '31/8/2026',
    trangThai: ETrangThaiKhuyenMai.DANG_CHAY,
    hoatDong: true,
  },
  {
    id: 'cb3',
    ten: 'Combo chay đặc biệt',
    moTa: 'Đậu hũ + cà phê sữa thanh đạm',
    monAnIds: ['m11', 'm12', 'm6'],
    loaiGia: ELoaiGiaCombo.PHAN_TRAM,
    giaTriGiam: 15,
    hetHan: '15/7/2026',
    trangThai: ETrangThaiKhuyenMai.SAP_HET,
    hoatDong: true,
  },
];

export const TRANG_THAI_KM_CONFIG: Record<
  ETrangThaiKhuyenMai,
  { label: string; color: string; bg: string }
> = {
  [ETrangThaiKhuyenMai.DANG_CHAY]: { label: 'Đang chạy', color: '#16a34a', bg: '#dcfce7' },
  [ETrangThaiKhuyenMai.SAP_HET]:   { label: 'Sắp hết',   color: '#d97706', bg: '#fef3c7' },
  [ETrangThaiKhuyenMai.TAM_DUNG]:  { label: 'Tạm dừng',  color: '#6b7280', bg: '#f3f4f6' },
  [ETrangThaiKhuyenMai.HET_HAN]:   { label: 'Hết hạn',   color: '#dc2626', bg: '#fee2e2' },
};
